# Build stage
FROM node:20-alpine as build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY shared/package*.json ./shared/
COPY services/mcsreact/package*.json ./services/mcsreact/

# Install dependencies
RUN npm install --verbose
RUN npm install --verbose --prefix shared
RUN npm install --verbose --prefix services/mcsreact

# Copy the rest of the code
COPY shared ./shared
COPY services/mcsreact ./services/mcsreact

# Build the shared package
WORKDIR /app/shared
RUN npm run build

# Build the React app
WORKDIR /app/services/mcsreact
RUN npm run build

# Set environment variables
ENV NODE_ENV=production
ENV REACT_APP_API_BASE_URL=http://localhost:5020
ENV REACT_APP_WS_URL=ws://localhost:5020

# Serve stage
FROM nginx:alpine

# Copy the build output to replace the default nginx contents
COPY --from=build /app/services/mcsreact/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80


# Start the application
CMD ["nginx", "-g", "daemon off;"]