# Use an official Node.js runtime as the base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
COPY package-lock.json ./
COPY shared/package*.json ./shared/
COPY errorhandler/package*.json ./errorhandler/
COPY services/missioncontrol/package*.json ./services/missioncontrol/

# Install the application dependencies
RUN npm install
RUN cd shared && npm install
RUN cd errorhandler && npm install
RUN cd services/missioncontrol && npm install

# Copy the application code to the working directory
COPY shared ./shared
COPY errorhandler ./errorhandler
COPY services/missioncontrol ./services/missioncontrol

# Build the TypeScript code - ensure shared is built first
RUN cd shared && npm run build
RUN cd errorhandler && npm run build
RUN npm run build --workspace=services/missioncontrol

# Set the working directory to the service
WORKDIR /usr/src/app/services/missioncontrol

# Expose the port the app runs on
EXPOSE 5030

# Define the command to run the application
CMD ["node", "dist/MissionControl.js"]