FROM node:22-alpine

RUN apk add --no-cache python3 make g++ vips-dev

WORKDIR /usr/src/app

COPY package*.json ./
COPY shared-nextgen/package*.json ./shared-nextgen/
COPY services ./services

RUN npm install --legacy-peer-deps

COPY shared-nextgen ./shared-nextgen
COPY services/worker-pool ./services/worker-pool

RUN cd shared-nextgen && npm run build
RUN cd services/worker-pool && rm -rf dist && npm run build

WORKDIR /usr/src/app/services/worker-pool

EXPOSE 3200

CMD ["node", "dist/index.js"]
