FROM node:22-alpine

RUN apk add --no-cache python3 make g++ vips-dev

WORKDIR /usr/src/app

COPY package*.json ./
COPY shared-nextgen/package*.json ./shared-nextgen/
COPY services ./services

RUN npm install --legacy-peer-deps

COPY shared-nextgen ./shared-nextgen
COPY services/artifacts ./services/artifacts

RUN cd shared-nextgen && npm run build
RUN cd services/artifacts && rm -rf dist && npm run build

WORKDIR /usr/src/app/services/artifacts

EXPOSE 4200

CMD ["node", "dist/index.js"]