FROM node:22-alpine as builder
WORKDIR /app/frontend-nextgen
COPY frontend-nextgen/package*.json ./
RUN npm install
COPY frontend-nextgen ./
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/frontend-nextgen/dist /usr/share/nginx/html
COPY frontend-nextgen/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
