import { createQuickAssistant } from '@cktmcs/sdk';

// Start the Restaurant Operations Assistant using the simplified SDK pattern
createQuickAssistant({
  id: 'restaurant-ops-assistant',
  name: 'Restaurant Operations Assistant',
  role: 'Assists with restaurant operations including reservations, staff scheduling, kitchen coordination, menu engineering, inventory management, and financial analytics',
  personality: 'Professional, efficient, detail-oriented, and service-focused',
  serviceId: 'restaurant-ops-assistant',
  secretEnvVar: 'RESTAURANT_OPS_ASSISTANT_API_SECRET',
  tools: async (coreEngineClient) => {
    const {
      ReservationSystemTool,
      TableManagementTool,
      GuestProfileTool,
      ServiceFlowTool,
      FloorManagementTool,
      StaffSchedulerTool,
      DemandForecastTool,
      LaborAnalyticsTool,
      ServerCommunicationTool,
      PrepSchedulerTool,
      KitchenDisplayTool,
      StationCoordinatorTool,
      RecipeManagementTool,
      RecipeCostingTool,
      MenuEngineeringTool,
      MenuOptimizerTool,
      PricingStrategyTool,
      InventoryTool,
      PurchaseOrderTool,
      SupplierManagementTool,
      OrderOptimizerTool,
      WasteManagementTool,
      PriceTrackingTool,
      FinancialAnalyticsTool,
      VarianceAnalysisTool,
      TrendAnalysisTool,
      SalesAnalyticsTool,
      ReservationAnalyticsTool,
      TableTurnoverTool,
      QualityControlTool,
      GuestFeedbackTool,
    } = await import('@cktmcs/sdk');

    return [
      new ReservationSystemTool(coreEngineClient),
      new TableManagementTool(coreEngineClient),
      new GuestProfileTool(coreEngineClient),
      new ServiceFlowTool(coreEngineClient),
      new FloorManagementTool(coreEngineClient),
      new StaffSchedulerTool(coreEngineClient),
      new DemandForecastTool(coreEngineClient),
      new LaborAnalyticsTool(coreEngineClient),
      new ServerCommunicationTool(coreEngineClient),
      new PrepSchedulerTool(coreEngineClient),
      new KitchenDisplayTool(coreEngineClient),
      new StationCoordinatorTool(coreEngineClient),
      new RecipeManagementTool(coreEngineClient),
      new RecipeCostingTool(coreEngineClient),
      new MenuEngineeringTool(coreEngineClient),
      new MenuOptimizerTool(coreEngineClient),
      new PricingStrategyTool(coreEngineClient),
      new InventoryTool(coreEngineClient),
      new PurchaseOrderTool(coreEngineClient),
      new SupplierManagementTool(coreEngineClient),
      new OrderOptimizerTool(coreEngineClient),
      new WasteManagementTool(coreEngineClient),
      new PriceTrackingTool(coreEngineClient),
      new FinancialAnalyticsTool(coreEngineClient),
      new VarianceAnalysisTool(coreEngineClient),
      new TrendAnalysisTool(coreEngineClient),
      new SalesAnalyticsTool(coreEngineClient),
      new ReservationAnalyticsTool(coreEngineClient),
      new TableTurnoverTool(coreEngineClient),
      new QualityControlTool(coreEngineClient),
      new GuestFeedbackTool(coreEngineClient),
    ];
  },
  port: parseInt(process.env.PORT || '3017'),
  urlBase: 'restaurant-ops-assistant-api',
}).catch((error: Error) => {
  console.error('Failed to initialize Restaurant Operations Assistant:', error);
  process.exit(1);
});
